project_name: netbird-ui
builds:
  - id: netbird-ui-darwin
    dir: client/ui
    binary: netbird-ui
    env: [CGO_ENABLED=1]

    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    gomips:
      - hardfloat
      - softfloat
    ldflags:
      - -s -w -X github.com/netbirdio/netbird/client/ui/system.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -X main.builtBy=goreleaser
    mod_timestamp: '{{ .CommitTimestamp }}'
    tags:
      - load_wgnt_from_rsrc

archives:
  - builds:
      - netbird-ui-darwin

  - id: netbird-app
    builds:
      - netbird-ui-darwin
    format: zip
    name_template: "{{ .ProjectName }}_app_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    files:
      - src: client/ui/Info.plist
        strip_parent: true
        dst: ./
      - src: client/ui/Netbird.icns
        dst: ./
        strip_parent: true
