name: Test Code Windows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/upload-artifact@v2
        with:
          name: dll
          path: client/*.dll

  test:
    needs: pre
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.x

      - uses: actions/cache@v2
        with:
          path: |
            %LocalAppData%\go-build
            ~\go\pkg\mod
            ~\AppData\Local\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: actions/download-artifact@v2
        with:
          name: dll
          path: C:\Windows\System32\

      - name: Test
        run: go test -timeout 5m -p 1 ./...