name: Test Code Windows

on:
  push:
    branches:
      - main
  pull_request:

env:
  downloadPath: '${{ github.workspace }}\temp'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || github.actor_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19.x

      - name: Download wintun
        uses: carlosperate/download-file-action@v2
        id: download-wintun
        with:
          file-url: https://www.wintun.net/builds/wintun-0.14.1.zip
          file-name: wintun.zip
          location: ${{ env.downloadPath }}
          sha256: '07c256185d6ee3652e09fa55c0b673e2624b565e02c4b9091c79ca7d2f24ef51'

      - name: Decompressing wintun files
        run: tar -zvxf "${{ steps.download-wintun.outputs.file-path }}" -C ${{ env.downloadPath }}

      - run: mv ${{ env.downloadPath }}/wintun/bin/amd64/wintun.dll 'C:\Windows\System32\'

      - name: Download PSTools
        uses: carlosperate/download-file-action@v2
        id: download-pstools
        with:
          file-url: https://download.sysinternals.com/files/PSTools.zip
          file-name: PSTools.zip
          location: ${{ env.downloadPath }}

      - name: Decompressing PSTools files
        run: tar -zvxf "${{ steps.download-pstools.outputs.file-path }}" -C ${{ env.downloadPath }}
      - run: dir ${{ github.workspace }}
      - run: ${{ env.downloadPath }}\PsExec64.exe -accepteula -s  powershell.exe -command "dir ${{ github.workspace }}"
      - name: Test
        run: ${{ env.downloadPath }}\PsExec64.exe -accepteula -s  powershell.exe -command "go test -timeout 5m -p 1 ${{ github.workspace }}\..."